services:
  aapanel:
    images: ubuntu:22.04
    container_name: "aapanel-webserver"
    restart: unless-stopped
    ports:
      - "${AAPANEL_PORT}:7800"
      - "${WEBSERVER_HOST_PORT}:80"
      - "${WEBSERVER_SECURE_HOST_PORT}:443"
      - "${PHPMYADMIN_PORT}:888"
      - "${REDIS_PORT}:6379"
      - "${SQL_PORT}:3306"
    volumes:
      - ${WEBSITE_DATA}:/www
    env_file:
      - ./.env
